on:
  push:
    branches:
      - staging
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 5.x
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: expo publish --release-channel staging
